In [87]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Standardization request for input survey

- Year(s) of Major Renovation(s): comma-separated numerics only. 
- Seismic Upgrade Year: Should restrict to significant upgrades to the lateral force-resisting systems. comma-separated numerics only. 
- Floors Below Grade: is grade-fixity good enough for fixed? Should we model basement as floor 1?
- Primary dimension of the building (length) in main directions
- Higher priority on story heights
- Length of just LFRS (m)

### Handle Excel

A better output would be to ask the user to manually use Excel to export the first sheet to CSV.

In [88]:
'''
import os 
import pandas as pd
from pathlib import Path

file_path = os.getcwd()
proj_root = os.path.dirname(file_path)

refm_excel_path = Path(file_path) / 'refm.xlsx'
output_csv = 'refm.csv'

# convert first sheet of the excel
df = pd.read_excel(refm_excel_path, sheet_name=0)

df.to_csv(output_csv, index=False)
'''

"\nimport os \nimport pandas as pd\nfrom pathlib import Path\n\nfile_path = os.getcwd()\nproj_root = os.path.dirname(file_path)\n\nrefm_excel_path = Path(file_path) / 'refm.xlsx'\noutput_csv = 'refm.csv'\n\n# convert first sheet of the excel\ndf = pd.read_excel(refm_excel_path, sheet_name=0)\n\ndf.to_csv(output_csv, index=False)\n"

In [89]:
import mimlos.mimlos.inventory as inv
import mimlos
import os 
import pandas as pd
from pathlib import Path

In [90]:
file_path = os.getcwd()
raw_csv = Path(file_path) / 'refm.csv'
inventory = inv.Inventory.load_from_csv(raw_csv)

In [91]:
df_raw = inventory.df_raw
print(df_raw['Seismic Force Resisting System in the East-West Direction'].unique())
print(df_raw['Seismic Force Resisting System in the North-South Direction'].unique())
print(df_raw['Site Class'].unique())

['CIW' nan 'CSW' 'RMC' 'WLF' 'WLF-P9' 'URM' 'SBF' 'PCW']
['CIW' nan 'CSW' 'RMC' 'WLF' 'WLF-P9' 'URM' 'PCW']
['C' nan 'E' 'D']

In [92]:
inventory.inventory_df

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,FEMA P154 RVS Level 2 Screening S-Score,SEG Level 2 - SQST S-Score,Building: Collapse Likelihood,Building: Post Disaster Importance,Building: Occupancy,Building: Seismic Screening Data,Building: Seismic S Score,Building: Seismic Risk,Longitude,Latitude
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,0.3,0.3,8%,High Occupancy-A,1000+,NaN,1.1000000000000001,High,-123.120526,49.280063
173,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,1.0,2,1.3% and 0.016%,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271
199,273,NONM_7904_1261 Granville St_Granville Residence,1261 Granville St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.2,0.3,15%,High Occupancy,11-100,NaN,-0.5,High,-123.127323,49.276628
204,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,4.1,4.6,0.2%,Reception Centre,101-1000,NaN,2.7,Low,-123.043079,49.227204
205,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,1.1,1.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
206,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,NaN,24-Sep-25,Adequate,24-Sep-25,...,4.0,3.9,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
207,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,1.3,2.3,NaN,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204
222,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Partial (Exterior),24-Sep-25,...,1.2,#VALUE!,15%,Reception Centre,101-1000,NaN,-0.3,High,-123.039428,49.280804
223,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
224,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
225,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,#VALUE!,NaN,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804
231,294,CULT_1418_3102 Main St_Heritage Hall_MIXU,3102 Main St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,0.7,0.4,15%,Emergency Shelter,101-1000,NaN,0.2,High,-123.100839,49.257296

TODO: solve environment to install openseespy

## Property estimations

### Building strength

1) Identify latest year of code-renovations or construction
2) Match to NBCC code year

In [93]:
inventory.estimate_Vs()

In [94]:
inventory.inventory_df.columns

Index(['ID', 'Facility/Asset', 'Address', 'Review Phase', 'Approver',
       'Screener', 'Drawings', 'Desktop Review Date', 'Site Visit',
       'Site Review Date', 'Ready for Approval?', 'Approved?', 'Building Name',
       'Development Category Indicator', 'Custom: CoV Ownership Status',
       'SAP Building Number', 'Date Built', 'Year Built',
       'NBC Code Year (Original Building)',
       'Current Replacement Value (June 2026)',
       'Gross Size (sq.ft.) - from Asset Planner - June 2026', 'CRV/sq.ft.',
       'Floors Above Grade', 'Floors Below Grade', 'Building: General Summary',
       'Building: Architectural Summary', 'Building: Heritage',
       'Year(s) of Major Renovation(s)', 'Description of Major Renovation',
       'Building: Main Superstructure Material',
       'Vertical Load Bearing System', 'Roof System', 'Floor System',
       'Seismic Force Resisting System in the North-South Direction',
       'Seismic Force Resisting System in the East-West Direction',
       'Number of LDRS Bays in North-South Direction',
       'Number of LDRS Bays in East-West Direction', 'Seismic Upgrade Year',
       'Description of Seismic Upgrade', 'Seismic Upgrading Case',
       'Building Height (Total Height Above Ground (m) to Roof Slab)',
       '"Original" Building Importance Factor Ie',
       'Building Importance Factor Ie - Based on VBBL 2025 - Upgraded',
       'Occupancy Type', 'Service Group', 'Replacement Cost (June 2026 $$)',
       'At-risk Population: Y/N?', 'Site Class', 'Basement',
       'Basement Floor Plan Area (sq.m.)', 'Ground Floor Plan Area (sq.m.)',
       'Roof Plan Area (sq.m.)', 'Geological Hazards',
       'Significant Alterations or Deviations', 'Material Conditions',
       'Sesimic Isolation / Energy Dissipation Systems',
       'Separation / Distance from Adjacent Structures (mm)',
       'Pounding Type Input', 'Pounding Type', 'Vertical Irregularity Input',
       'Vertical Irregularity Description', 'Plan Irregularity Input',
       'Plan Irregularity Description', 'Building Irregularity',
       'Falling Hazards (Y/N)',
       'Exterior Non-structural Components - Restrained (Y/N)',
       'Interior Non-structural Components - Restrained (Y/N)', 'URM (Y/N)',
       'FEMA P154 Special Cases', 'Remaining Occupancy Time',
       'Category Functionality Class',
       'Gross Area (including basement) (sq.m.)', 'Seismic Weight (kN)',
       'Snow Load and Roof Weight (kN)', 'Floor Weight - Above Grade (kN)',
       'LDRS Weight North-South Direction (kN)',
       'LDRS Weight East-West Direction (kN)',
       'Content Weight Based on Occupancy Type (kN)',
       'FEMA P154 RVS Level 2 Screening S-Score', 'SEG Level 2 - SQST S-Score',
       'Building: Collapse Likelihood', 'Building: Post Disaster Importance',
       'Building: Occupancy', 'Building: Seismic Screening Data',
       'Building: Seismic S Score', 'Building: Seismic Risk', 'Longitude',
       'Latitude', 'latest_seismic_upgrade_year', 'original_nbcc_year',
       'effective_nbcc_year'],
      dtype='object')

In [95]:
inventory.inventory_df

,ID,Facility/Asset,Address,Review Phase,Approver,Screener,Drawings,Desktop Review Date,Site Visit,Site Review Date,...,Building: Post Disaster Importance,Building: Occupancy,Building: Seismic Screening Data,Building: Seismic S Score,Building: Seismic Risk,Longitude,Latitude,latest_seismic_upgrade_year,original_nbcc_year,effective_nbcc_year
0,12,CULT_1064_601 Smithe St_Orpheum Theatre,601 Smithe St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,19-Sep-25,Adequate,19-Sep-25,...,High Occupancy-A,1000+,NaN,1.1000000000000001,High,-123.120526,49.280063,<NA>,1927,1941
173,245,RECR_1337_5175 Dumfries St_Kensington Communit...,5175 Dumfries St,Phase 1,Monrit Gill,Pavan Dhillon,Adequate,17-Aug-26,Adequate,21-Aug-26,...,Emergency Shelter,101-1000,NaN,1.9,Medium,-123.074743,49.237271,<NA>,1995,1995
199,273,NONM_7904_1261 Granville St_Granville Residence,1261 Granville St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,High Occupancy,11-100,NaN,-0.5,High,-123.127323,49.276628,<NA>,1919,1941
204,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,Reception Centre,101-1000,NaN,2.7,Low,-123.043079,49.227204,<NA>,2005,2005
205,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204,<NA>,1995,1995
206,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,NaN,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204,<NA>,2005,2005
207,280,RECR_1821_6260 Killarney St_Killarney Communit...,6260 Killarney St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Adequate,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.043079,49.227204,<NA>,2005,2005
222,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Partial (Exterior),24-Sep-25,...,Reception Centre,101-1000,NaN,-0.3,High,-123.039428,49.280804,<NA>,1936,1941
223,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804,<NA>,1953,1953
224,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804,<NA>,1965,1965
225,288,RECR_4384_3096 E Hastings St_Hastings Communit...,3096 E Hastings St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,24-Sep-25,Adequate,24-Sep-25,...,NaN,NaN,NaN,NaN,NaN,-123.039428,49.280804,<NA>,1953,1953
231,294,CULT_1418_3102 Main St_Heritage Hall_MIXU,3102 Main St,Phase 1,Kate Thibert (Ausenco),Pavan Dhillon,Partial,18-Sep-25,Adequate,18-Sep-25,...,Emergency Shelter,101-1000,NaN,0.2,High,-123.100839,49.257296,<NA>,1914,1941

Tester

In [96]:
bldg_1941 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1941(bldg_1941)
print(vs_ns, vs_ew)

0.05 0.05

In [97]:
bldg_1953 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1953(bldg_1953)
print(vs_ns, vs_ew)

0.2 0.2

In [98]:
bldg_1965 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1965(bldg_1965)
print(vs_ns, vs_ew)

0.125 0.125

In [99]:
bldg_1970 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1970(bldg_1970)
print(vs_ns, vs_ew)

0.1 0.1

In [100]:
bldg_1975 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1975(bldg_1975)
print(vs_ns, vs_ew)

0.10400000000000001 0.10400000000000001

In [101]:
bldg_1985 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1985(bldg_1985)
print(vs_ns, vs_ew)

0.08800000000000001 0.08800000000000001

In [102]:
bldg_1990 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_1990(bldg_1990)
print(vs_ns, vs_ew)

0.18000000000000002 0.18000000000000002

In [103]:
bldg_2005 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_2005(bldg_2005)
print(vs_ns, vs_ew)

0.18464285714285714 0.18464285714285714

In [104]:
bldg_2010 = inventory.inventory_df.loc[223]
vs_ns, vs_ew = mimlos.mimlos.properties.vs_nbcc_2010(bldg_2010)
print(vs_ns, vs_ew)

0.18464285714285714 0.18464285714285714